name: Rubles
version: 1.0-SNAPSHOT
main: com.github.anton4k.rubles.Rubles
api-version: 1.16
commands:
  rubles:
    description: Manage Rubles currency
    usage: /rubles [add | remove | reload] [player] [amount]
permissions:
  rubles.use:
    description: Allows checking Rubles balance
    default: true
  rubles.add:
    description: Allows adding Rubles
    default: op
  rubles.remove:
    description: Allows removing Rubles
    default: op
  rubles.reload:
    description: Allows reloading the plugin configuration
    default: op
softdepend: [PlaceholderAPI]